### ISSUE TITLE
Can't set labels on issues in the git repo

### ISSUE THREAD

**Issue by sgibson-mse** [Logan125/python-intermediate-inflammation-#5]
No permissions given to add a label when raising an issue (I think we must become developers to be able to do so!)

**Comment by OceanNuclear** [comment]
According to the GitHub [managing labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#applying-a-label) link we must have [triage access](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization).

**Comment by Shan125485** [comment]
Not in our control
